# application.yml - Base Configuration
# This is the main application configuration file.
# We set 'dev' as the active profile by default so Spring Boot reads application-dev.yml automatically during local development.

spring:
  profiles:
    active: dev
  application:
    name: quicktix
