
spring:
  profiles:
    active: dev
  application:
    name: quicktix

# during deployment: We don't need to make 'profiles' as 'prod' - Just (spring.profile.active: PROD) at .env file at deployment

